WITH CTE AS(
SELECT 
	C.CustomerId,
	C.CustomerName,
	OrderDate,
	SUM(Quantity * PRICE) OVER (PARTITION BY C.CustomerId ORDER BY OrderDate) AS DailyOrders
FROM Customers C
LEFT JOIN Orders O
ON C.CustomerId = O.CustomerId
INNER JOIN Products P
ON O.ProductId = P.ProductId
)
SELECT CustomerName FROM (
SELECT 
	*,
	LAG(DailyOrders) OVER(PARTITION BY CUSTOMERID ORDER BY CUSTOMERID,ORDERDATE) AS PREV_DAY_SALE,
	LEAD(DailyOrders) OVER(PARTITION BY CUSTOMERID ORDER BY CUSTOMERID,ORDERDATE) AS NEXT_DAY_SALE
FROM CTE) AS T
WHERE (PREV_DAY_SALE>DailyOrders AND NEXT_DAY_SALE>DailyOrders);