WITH CTE AS(
SELECT 
	U.UserId,
	MR.MovieId,
	MR.RATING,
	ROW_NUMBER() OVER (PARTITION BY U.USERID ORDER BY RATING DESC) AS HIGHEST_RATED
FROM Users U
LEFT JOIN MovieRatings MR
ON U.UserId = MR.UserId
)
SELECT UserId,MovieId FROM CTE 
WHERE HIGHEST_RATED = 1
AND MovieId IS NOT NULL;