USE [AdventureWorks2022]
GO

/****** Object:  StoredProcedure [dbo].[sp_ETLLoadtoStaging]    Script Date: 11/16/2025 10:31:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER   PROCEDURE [dbo].[sp_ETLLoadtoStaging]
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY
		BEGIN TRANSACTION
			TRUNCATE TABLE STAGING_PRODUCT;
			INSERT INTO STAGING_PRODUCT SELECT * FROM Production.Product;
		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION;
		PRINT 'ERROR' + ERROR_MESSAGE();
	END CATCH
END;

GO

--EXEC sp_ETLLoadtoStaging