WITH CTE1 AS (
	SELECT
		CustomerID,
		OrderDate,
		LAG(OrderDate) OVER (PARTITION BY CUSTOMERID ORDER BY OrderDate) AS PrevOrderDate,
		CASE WHEN DATEDIFF(DAY,LAG(OrderDate) OVER (PARTITION BY CUSTOMERID ORDER BY OrderDate),OrderDate) > 7 
		OR LAG(OrderDate) OVER(PARTITION BY CUSTOMERID ORDER BY OrderDate) IS NULL
		THEN 1 ELSE 0
		END AS IsNewSession	
	FROM Sales.SalesOrderHeader
),
CTE2 AS (
	SELECT
		CustomerID,
		OrderDate,
		SUM(IsNewSession) OVER (PARTITION BY CUSTOMERID ORDER BY OrderDate ROWS UNBOUNDED PRECEDING) AS SessionID
	FROM CTE1
)
SELECT * FROM CTE2;
