SELECT 
	BirthDate,
	DATEDIFF(YEAR,BirthDate,GETDATE()) AS AGE,
	CASE 
		WHEN DATEDIFF(YEAR,BirthDate,GETDATE()) <20 THEN '<20'
		WHEN DATEDIFF(YEAR,BirthDate,GETDATE()) BETWEEN 20 AND 35 THEN '20-35'
		WHEN DATEDIFF(YEAR,BirthDate,GETDATE()) BETWEEN 36 AND 50 THEN '36-50'
		WHEN DATEDIFF(YEAR,BirthDate,GETDATE()) >50 THEN '>50'
	END AS AgeCategory
FROM HumanResources.Employee;