SELECT DISTINCT
	ProductID,
	FIRST_VALUE(ListPrice) OVER (PARTITION BY PRODUCTID ORDER BY ModifiedDate) AS FirstListPrice,
	LAST_VALUE(ListPrice) OVER(PARTITION BY PRODUCTID ORDER BY ModifiedDate ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS LastListPrice
FROM Production.ProductListPriceHistory;