WITH CTE AS(
SELECT 
	LogId,
	LAG(LogId) OVER (ORDER BY LogId) AS PREV_LOGID,
	LEAD(LogId) OVER(ORDER BY LogId) AS NEXT_LOGID
FROM Logs)
SELECT ConsecutiveNums FROM(
SELECT 
	CASE WHEN LogId = PREV_LOGID AND LogId=NEXT_LOGID THEN 1 ELSE 0 END AS FOUND,
	LogId AS ConsecutiveNums
FROM CTE) AS T
WHERE FOUND = 1;